//DATA
const productos = [
  // PORTÁTILES CORPORATIVOS
  {
    nombre: "Lenovo ThinkPad X1 Carbon",
    serial: "20FB00MEUS",
    modelo: "i7-1260P / 16GB / 512GB SSD / 14'' 4K",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Lenovo ThinkPad X1 Carbon.webp",
    codigo: "Th01X1CB",
    precio: 6899000,
    garantia: "1 años",
  },
  {
    nombre: "Dell Latitude 7430",
    serial: "L7430-i7",
    modelo: "i7-1265U / 32GB / 1TB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Dell Latitude 7430.webp",
    codigo: "DL74i7",
    precio: 7299000,
    garantia: "1 años",
  },
  // PORTÁTILES GAMING
  {
    nombre: "MSI Raider GE78 HX",
    serial: "GE78-13VH",
    modelo: "i9-13950HX / 64GB / 2TB SSD / RTX 4090 / 17'' QHD",
    categoria: "portatil gamer",
    imagen: "../img/IMAGENES DATA/MSI Raider GE78 HX.webp",
    codigo: "MS78GE",
    precio: 15990000,
    garantia: "1 años",
  },
  {
    nombre: "Razer Blade 16",
    serial: "RZ09-0483",
    modelo: "i9-13950HX / 32GB / 1TB SSD / RTX 4080 / 16'' 4K",
    categoria: "portatil gamer",
    imagen: "../img/IMAGENES DATA/Razer Blade 16.jpg",
    codigo: "RB16-4K",
    precio: 13990000,
    garantia: "1 años",
  },
  // COMPUTADORES DE ESCRITORIO
  {
    nombre: "PC Gaming Pro",
    serial: "PCGP-13900K",
    modelo: "i9-13900K / 64GB / 2TB SSD / RTX 4080 / Monitor 32'' 4K",
    categoria: "escritorio",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "GP13900",
    precio: 12990000,
    garantia: "1 años",
  },
  {
    nombre: "PC Workstation",
    serial: "WS-TR64",
    modelo: "Threadripper 7980X / 128GB / 4TB SSD / RTX 4090 / Monitor 32'' 8K",
    categoria: "escritorio",
    imagen: "../img/IMAGENES DATA/PC Workstation.jpeg",
    codigo: "WS7980",
    precio: 19990000,
    garantia: "1 años",
  },
  // PERIFÉRICOS - TECLADOS
  {
    nombre: "Teclado Logitech G Pro X",
    serial: "920-009388",
    modelo: "Mecánico / RGB / Switch GX Blue / QWERTY",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Teclado Logitech G Pro X.webp",
    codigo: "LGPX-KB",
    precio: 699000,
    garantia: "1 años",
  },
  {
    nombre: "Teclado Razer Huntsman V2",
    serial: "RZ03-03930100",
    modelo: "Óptico / RGB / Switch Analog / QWERTY",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Teclado Razer Huntsman V2.jpg",
    codigo: "RZ-HV2",
    precio: 899000,
    garantia: "1 años",
  },
  // PERIFÉRICOS - AUDÍFONOS
  {
    nombre: "Audífonos HyperX Cloud Alpha",
    serial: "4P5L9AA",
    modelo: "Wireless / 7.1 / 300h Batería",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Audífonos HyperX Cloud Alpha.webp",
    codigo: "HX-CHA",
    precio: 599000,
    garantia: "1 años",
  },
  {
    nombre: "Audífonos SteelSeries Arctis Nova Pro",
    serial: "61552",
    modelo: "Wireless / Hi-Fi / ANC / 360° Audio",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Audífonos SteelSeries Arctis Nova Pro.png",
    codigo: "SS-ANP",
    precio: 1299000,
    garantia: "1 años",
  },
  // IMPRESORAS
  {
    nombre: "Epson EcoTank L8180",
    serial: "C11CJ21301",
    modelo: "A3+ / 6 Colores / WiFi / Duplex",
    categoria: "impresora",
    imagen: "../img/IMAGENES DATA/Epson EcoTank L8180.webp",
    codigo: "EP-L8180",
    precio: 3499000,
    garantia: "1 año",
  },
  {
    nombre: "HP LaserJet Enterprise M507x",
    serial: "1PV88A",
    modelo: "Monocromática / 45ppm / Duplex / Red",
    categoria: "impresora",
    imagen: "../img/IMAGENES DATA/HP LaserJet Enterprise M507x.jpg",
    codigo: "HP-M507X",
    precio: 2899000,
    garantia: "1 año",
  },
  // ACCESORIOS
  {
    nombre: "Webcam Logitech Brio 4K",
    serial: "960-001105",
    modelo: "4K Ultra HD / HDR / 90fps",
    categoria: "accesorio",
    imagen: "../img/IMAGENES DATA/Webcam Logitech Brio 4K.png",
    codigo: "LG-BRIO",
    precio: 799000,
    garantia: "1 años",
  },
  {
    nombre: "Base Refrigerante Thermaltake Massive",
    serial: "CL-N014-PL20BL-A",
    modelo: 'RGB / 20" / 2 Ventiladores',
    categoria: "accesorio",
    imagen: "../img/IMAGENES DATA/Base Refrigerante Thermaltake Massive.jpg",
    codigo: "TT-M20",
    precio: 189000,
    garantia: "1 año",
  },
  // CORPORATIVOS
  {
    nombre: "Dell Latitude 3450",
    serial: "9CKND",
    modelo: "i7-1355U / 16GB / 512GB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Dell Latitude 3450.jpg",
    codigo: "Nh08J8K5R",
    precio: 4459000,
    garantia: "1 año",
  },
  {
    nombre: "Dell Latitude 3440",
    serial: "NK94V",
    modelo: "i5-1235U / 8GB / 512GB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Dell Latitude 3440.jpeg",
    codigo: "Lk27Y3WZP",
    precio: 4059000,
    garantia: "1 año",
  },
  {
    nombre: "Dell Inspiron 3530",
    serial: "F9FRR",
    modelo: "i5-1334U / 8GB / 512GB SSD / 15.6''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Dell Inspiron 3530.jpg",
    codigo: "Yp45M6BVR",
    precio: 3900000,
    garantia: "1 año",
  },
  {
    nombre: "Dell Inspiron 3520",
    serial: "G5M42",
    modelo: "i5-1235U / 8GB / 512GB SSD / 15.6''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Dell Inspiron 3520.webp",
    codigo: "Xf12T9QWE",
    precio: 3780000,
    garantia: "1 año",
  },
  {
    nombre: "Lenovo ThinkPad L14",
    serial: "20X2S8DH00_I",
    modelo: "i5-1135G7 / 8GB / 256GB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Lenovo ThinkPad L14.jpeg",
    codigo: "Qz93L2MNV",
    precio: 4290000,
    garantia: "1 años",
  },
  {
    nombre: "Lenovo ThinkPad E14",
    serial: "21JLS6EQ00",
    modelo: "i5-1335U / 16GB / 512GB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Lenovo ThinkPad E14.webp",
    codigo: "Bs76F4JUC",
    precio: 4249000,
    garantia: "1 año",
  },
  {
    nombre: "Lenovo ThinkPad T14S",
    serial: "20WNS1TT00",
    modelo: "i7-1165G7 / 8GB / 512GB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Lenovo ThinkPad T14S.webp",
    codigo: "Tm50K3VDL",
    precio: 6190000,
    garantia: "1 años",
  },
  {
    nombre: "Lenovo ThinkPad L14 Gen 4",
    serial: "21H2001DLM",
    modelo: "i5-1335U / 16GB / 512GB SSD / 14''",
    categoria: "portatil",
    imagen: "../img/IMAGENES DATA/Lenovo ThinkPad L14 Gen 4.webp",
    codigo: "Dr63B9XQP",
    precio: 4299000,
    garantia: "1 años",
  },
  // PORTÁTILES GAMER
  {
    nombre: "Asus ROG Strix 18",
    serial: "G834JY-N6016W",
    modelo: "i9-13980HX / 32GB / 1TB SSD / RTX 4090 / 18''",
    categoria: "portatil gamer",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Zp81F6LRJ",
    precio: 13990000,
    garantia: "1 año",
  },
  {
    nombre: "Asus TUF Gaming A15",
    serial: "FA507NUR-LP005",
    modelo: "Ryzen 7 7435HS / 16GB / 512GB SSD / RTX 4050 / 15.6''",
    categoria: "portatil gamer",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Zo284X6DF",
    precio: 4920000,
    garantia: "1 año",
  },
  {
    nombre: "Asus ROG Zephyrus G16",
    serial: "GU605MI-QR049W",
    modelo: "Ultra 9 / 32GB / 1TB SSD / RTX 4070 / 16'' 2.5K",
    categoria: "portatil gamer",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Kx45M2TPR",
    precio: 11100000,
    garantia: "1 año",
  },
  // PORTÁTILES DE CONSUMO
  {
    nombre: "HP 255 G9",
    serial: "84B63LT#ABM",
    modelo: "Ryzen 5 7520U / 8GB / 256GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/HP 255 G9.png",
    codigo: "Wq72L9FXR",
    precio: 1589000,
    garantia: "1 año",
  },
  {
    nombre: "HP 255 G9",
    serial: "84B64LT#ABM",
    modelo: "Ryzen 7 7730U / 8GB / 512GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/HP 255 G9 (2).png",
    codigo: "Vc31P5TYZ",
    precio: 1989000,
    garantia: "1 año",
  },
  {
    nombre: "Lenovo V15 G4",
    serial: "82YU00R3LM",
    modelo: "Ryzen 5 7520U / 8GB / 256GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/Lenovo V15 G4.webp",
    codigo: "Jm84K7QBV",
    precio: 1519000,
    garantia: "1 año",
  },
  {
    nombre: "Lenovo V15 G4",
    serial: "82YU00R2LM",
    modelo: "Ryzen 3 7320U / 8GB / 256GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/Lenovo V15 G4 (2).webp",
    codigo: "Bp16X4MVR",
    precio: 1379000,
    garantia: "1 año",
  },
  {
    nombre: "Asus Vivobook Go 15",
    serial: "E1504GA-NJ184W",
    modelo: "Intel Core i3 N305 / 8GB / 256GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Uf03Z6DPT",
    precio: 1449000,
    garantia: "1 año",
  },
  {
    nombre: "Asus Vivobook 15",
    serial: "X1504ZA-NJ187W",
    modelo: "Intel Core i5-1235U / 8GB / 512GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Tn68Y9LWC",
    precio: 1899000,
    garantia: "1 año",
  },
  {
    nombre: "HP 255 G9",
    serial: "84B65LT#ABM",
    modelo: "Ryzen 3 7320U / 8GB / 256GB SSD / 15.6''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/HP 255 G9 (3).png",
    codigo: "Zk57A3REV",
    precio: 1349000,
    garantia: "1 año",
  },
  {
    nombre: "Lenovo IdeaPad 1 14",
    serial: "82V6S0WJLM",
    modelo: "Intel Core i3 N305 / 8GB / 256GB SSD / 14''",
    categoria: "portatil consumo",
    imagen: "../img/IMAGENES DATA/Lenovo IdeaPad 1 14.webp",
    codigo: "Lp22C5MTJ",
    precio: 1279000,
    garantia: "1 año",
  },
  // ALL IN ONE Y PC ENSAMBLADOS
  {
    nombre: "PC Gaming",
    serial: "ENSAMB_12400",
    modelo: "i5 12400 / 8GB / 480GB SSD / Monitor 19''",
    categoria: "ensamblado",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Vf64N3TQX",
    precio: 1699000,
    garantia: "1 año",
  },
  {
    nombre: "PC Gaming Pro",
    serial: "ENSAMB_5600G",
    modelo: "Ryzen 5 5600G / 16GB / 480GB SSD / Monitor 19''",
    categoria: "ensamblado",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Qz35M1KPV",
    precio: 1799000,
    garantia: "1 año",
  },
  {
    nombre: "PC Gaming Elite",
    serial: "ENSAMB_5600G_1TB",
    modelo: "Ryzen 5 5600G / 16GB / 1TB SSD / Monitor 22''",
    categoria: "ensamblado",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Bp97X6LER",
    precio: 2099000,
    garantia: "1 año",
  },
  {
    nombre: "PC Gaming Ultimate",
    serial: "ENSAMB_5700G",
    modelo: "Ryzen 7 5700G / 16GB / 1TB SSD / Monitor 22''",
    categoria: "ensamblado",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Jt21V4MNC",
    precio: 2499000,
    garantia: "1 año",
  },
  // TARJETAS DE VIDEO
  {
    nombre: "NVIDIA GeForce GT 730",
    serial: "VCGGT7302D3LXPB",
    modelo: "GT 730 / 2GB DDR3 / 64 bits / PCIe",
    categoria: "tarjeta grafica",
    imagen: "../img/IMAGENES DATA/NVIDIA GeForce GT 730.jpg",
    codigo: "Fg72M8WZR",
    precio: 319000,
    garantia: "1 año",
  },
  {
    nombre: "ASUS Phoenix GTX 1650 OC",
    serial: "PH-GTX1650-O4GD6",
    modelo: "GTX 1650 / 4GB GDDR6 / HDMI-DP-DVI / PCIe",
    categoria: "tarjeta grafica",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Rt61V4LBN",
    precio: 799000,
    garantia: "1 año",
  },
  {
    nombre: "ASUS Dual RTX 4060",
    serial: "DUAL-RTX4060-O8G",
    modelo: "RTX 4060 / 8GB GDDR6 / HDMI-DP / PCIe",
    categoria: "tarjeta grafica",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Yx43K9UPT",
    precio: 1599000,
    garantia: "1 año",
  },
  {
    nombre: "ASUS Dual RTX 4060 Ti",
    serial: "DUAL-RTX4060TI-O8G",
    modelo: "RTX 4060 Ti / 8GB GDDR6 / HDMI-DP / PCIe",
    categoria: "tarjeta grafica",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Lq38T7FDM",
    precio: 2149000,
    garantia: "1 año",
  },
  {
    nombre: "ASUS Dual RTX 4070 Super",
    serial: "DUAL-RTX4070S-O12G",
    modelo: "RTX 4070 Super / 12GB GDDR6X / HDMI-DP / PCIe",
    categoria: "tarjeta grafica",
    imagen: "../img/IMAGENES DATA/PC Gaming Pro.webp",
    codigo: "Kp89X1GER",
    precio: 2849000,
    garantia: "1 año",
  },
  // PERIFÉRICOS - MOUSES GAMER
  {
    nombre: "Mouse Gamer Logitech G203",
    serial: "910-005790",
    modelo: "RGB / 8000 DPI / 6 Botones / Negro",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Mouse Gamer Logitech G203.webp",
    codigo: "Rq38L5WDT",
    precio: 72900,
    garantia: "1 años",
  },
  {
    nombre: "Mouse Gamer Razer DeathAdder V3 Pro",
    serial: "RZ01-0050",
    modelo: "30K DPI / Wireless / 90h Batería / Blanco",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Mouse Gamer Razer DeathAdder V3 Pro.jpg",
    codigo: "Hd95W2KMT",
    precio: 699000,
    garantia: "1 años",
  },
  {
    nombre: "Mouse Gamer SteelSeries Prime Pro",
    serial: "62533",
    modelo: "18K DPI / RGB / Magnetic Switches",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Mouse Gamer SteelSeries Prime Pro.webp",
    codigo: "Nv27R8PXT",
    precio: 399000,
    garantia: "1 años",
  },
  {
    nombre: "Mouse Gamer Corsair M65 Pro RGB",
    serial: "CH-9309011",
    modelo: "18K DPI / RGB / Peso Ajustable",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Mouse Gamer Corsair M65 Pro RGB.webp",
    codigo: "Bk41H6LWS",
    precio: 289000,
    garantia: "1 años",
  },
  {
    nombre: "Mousepad Razer Strider Chroma",
    serial: "RZ02-0420",
    modelo: "RGB / 900x370mm / Hybrid Surface",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Mousepad Razer Strider Chroma.jpg",
    codigo: "Ym63T9NQW",
    precio: 299000,
    garantia: "1 años",
  },
  {
    nombre: "Mousepad SteelSeries QcK Prism",
    serial: "63826",
    modelo: "RGB / 900x300mm / Micro-Woven",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Mousepad SteelSeries QcK Prism.webp",
    codigo: "Px18D4VHT",
    precio: 249000,
    garantia: "1 años",
  },
  {
    nombre: "Webcam Razer Kiyo Pro",
    serial: "RZ19-0370",
    modelo: "1080p / 60FPS / HDR / USB 3.0",
    categoria: "accesorio",
    imagen: "../img/IMAGENES DATA/Webcam Razer Kiyo Pro.webp",
    codigo: "Wc74M1BNK",
    precio: 599000,
    garantia: "1 año",
  },
  {
    nombre: "Micrófono HyperX QuadCast S",
    serial: "HMIQ1S-XX-RG/G",
    modelo: "RGB / USB / 4 Patrones / Anti-Vibración",
    categoria: "periferico",
    imagen: "../img/IMAGENES DATA/Micrófono HyperX QuadCast S.jpeg",
    codigo: "Mc92K7LHT",
    precio: 799000,
    garantia: "1 años",
  },
];

console.log(productos.length);

//REGISTRO
const formulario = document.getElementById("myForm");

formulario.addEventListener("submit", (evitarReset) => {
  evitarReset.preventDefault(); //evita reseteo de campos al presionar el boton de registrar

  const nombre = document.getElementById("nombre").value; //ese "nombre" es el ID del input
  console.log(nombre);

  const serial = document.getElementById("serial").value; 
  console.log(serial);

  const modelo = document.getElementById("modelo").value; 
  console.log(modelo);

  const categoria = document.getElementById("categoria").value;
  console.log(categoria);

  const imagen = document.getElementById("imagen").value;
  console.log(imagen);

  const codigo = document.getElementById("codigo").value;
  console.log(codigo);

  const precio = document.getElementById("precio").value;
  console.log(precio);

  const garantia = document.getElementById("garantia").value;
  console.log(garantia);
});
